### ISSUE TITLE
Implement Typeracer

### ISSUE THREAD

**Issue by zeffo** [zeffo/HK#3]

**Comment by zeffo** [comment]
@mudkipdev I'm going to close this soon... are you still interested in implementing it or should I ask Brandon to

**Comment by mudkipdev** [comment]
@zeffo I will implement it! Remind me to on Discord in the next couple days and I will make sure to set aside some time for it.

**Comment by zeffo** [comment]
> @zeffo I will implement it! Remind me to on Discord in the next couple days and I will make sure to set aside some time for it.

Chatgpt-ass response
